import {
  postLinkLength,
  postTitleLength,
  postSubtitleLength,
  postSummaryLength,
  adminUsernameLength,
  adminEmailLength,
  adminOtpLength,
  partnerNameLength,
  partnerStoreNameLength,
  partnerVatLength,
  partnerDoyLength,
  partnerEmailLength,
  partnerPhoneLength,
  partnerSiteUrlLength,
  partnerOtpLength,
  productNameLength,
  productDescriptionLength,
  productShortDescriptionLength,
} from "./db-fields";

import { doys } from "./doy";

export {
  doys,
  postLinkLength,
  postTitleLength,
  postSubtitleLength,
  postSummaryLength,
  adminUsernameLength,
  adminEmailLength,
  adminOtpLength,
  partnerNameLength,
  partnerStoreNameLength,
  partnerVatLength,
  partnerDoyLength,
  partnerEmailLength,
  partnerPhoneLength,
  partnerSiteUrlLength,
  partnerOtpLength,
  productNameLength,
  productDescriptionLength,
  productShortDescriptionLength,
};
